/**
 * One icon module. Every icon in the app resolves from here, so swapping the
 * icon set never touches a view. PROJECT_CONTEXT.md §9.1.
 */

export {
  VideoCamera as IconVision,
  Thermometer as IconThermal,
  MapTrifold as IconMap,
  Leaf as IconEnvironment,
  UserFocus as IconPersonnel,
  ShieldCheck as IconHealth,
  GameController as IconControl,
  ClipboardText as IconReports,
  ArrowLeft as IconBack,
  Warning as IconWarning,
  WarningCircle as IconCritical,
  Info as IconAttention,
  CheckCircle as IconNormal,
  Question as IconUnknown,
  BatteryHigh as IconBattery,
  WifiHigh as IconConnected,
  WifiSlash as IconDisconnected,
  Sun as IconLight,
  Moon as IconDark,
  Play as IconPlay,
  Stop as IconStop,
  BookmarkSimple as IconBookmark,
  MagnifyingGlass as IconSearch,
  Gauge as IconSpeed,
  CaretUp as IconUp,
  CaretDown as IconDown,
  CaretLeft as IconLeft,
  CaretRight as IconRight,
  Crosshair as IconLocate,
  Pulse as IconPulse,
  Plugs as IconSource,
  ArrowClockwise as IconRetry,
  Fire as IconHeat,
  Ruler as IconDistance,
  Drop as IconHumidity,
  Wind as IconPressure,
  Cpu as IconAi,
  HardDrives as IconNode,
  FileText as IconDocument,
  Rewind as IconReplay,
  GearSix as IconSettings,
  ArrowsClockwise as IconReload,
  ArrowCounterClockwise as IconReset,
  Plus as IconPlus,
  TrashSimple as IconTrash,
  Flask as IconMock,
  Broadcast as IconLive,
  NavigationArrow as IconGps,
  Radio as IconRadio,
  SpeakerHigh as IconAudioOn,
  SpeakerSlash as IconAudioOff,
} from "@phosphor-icons/react";

export type { Icon as IconComponent } from "@phosphor-icons/react";
